[component]
structures = [ "content_blocks" ]
label = "Review"
description = "Review Section with heading, a image, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Recent Works"
description_html = "Vonge review features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful review or how to make yours even better!"
link_url = "/el-corgi-pretencioso"
show_posts = true